Ingest tarball leading slashes
cvmfs/cvmfs pull request #2593
Opened 2020-08-17 10:59 UTC by siscia

Fix the ingestion of tarballs when the file inside the tarball present leading slashes.

2020-08-17 11:37 UTC, jblomer requested changes
Looks in principal good to me, just one suggestion for an improvement.

2020-08-17 11:37 UTC, jblomer commented on cvmfs/sync_union_tarball.cc
> +      to_return.erase(0, 1);
Side note, why not simply return `path.substr(1)`.

2020-08-17 11:41 UTC, jblomer commented
Please also add a PR for the backport to the 2.7 branch

2020-08-17 13:06 UTC, jblomer approved these changes

2020-08-17 13:10 UTC, siscia commented
Still something isn't working quite alright in the test machine... Looking into it.

2020-08-19 15:12 UTC, jblomer commented
@cernvm-bot cloudtest

2020-08-20 07:35 UTC, merged