Debian Packaging: Only recommend apache2
cvmfs/cvmfs pull request #2598
Opened 2020-09-02 11:36 UTC by ChristianTackeGSI

cvmfs-server currently strictly depends on apache2.
On a publisher node, one does not need apache2.
So turn the "Depends: apache2" into a "Recommends: apache2".

Recommends means "You really should install this. If you don't, expect missing functionality". Which fits very well: If one does not install apache2, one can't run a stratum-0.

2020-09-02 11:57 UTC, jblomer commented
@cernvm-bot cloudtest

2020-09-03 21:58 UTC, jblomer requested changes
Many thanks!  Looks in principle good to me.  Could you also add `apache2` as an explicit package to test/cloud_testing/platforms/ubuntu_setup.sh

That should fix the integration tests

2020-09-04 00:26 UTC, ChristianTackeGSI commented
done.

I have not tested this! So I hope your CI will do that now.

2020-09-04 06:26 UTC, jblomer commented
@cernvm-bot cloudtest

2020-09-04 08:30 UTC, jblomer approved these changes

2020-09-04 08:30 UTC, merged

2020-09-04 08:32 UTC, jblomer commented
Thanks!  It won't make it in the 2.7.4 patch release that we are cutting just now but it will be part of the 2.8 release.

2020-09-04 09:08 UTC, ChristianTackeGSI commented
> Thanks! It won't make it in the 2.7.4 patch release that we are cutting just now but it will be part of the 2.8 release.

Thanks! 2.8 is fine. It will just simplify our setup a bit.