remove build.sh and replace with self contained Dockerfile
cvmfs/cvmfs pull request #2604
Opened 2020-09-16 09:27 UTC by siscia

2020-09-16 16:29 UTC, siscia commented
This runs into problem when we want to build against commits that are not in the main repo, like PR.

Not sure there is a clean way around it thought.

2020-09-17 09:14 UTC, jblomer commented
@cernvm-bot cloudtest container

2020-09-17 09:59 UTC, jblomer requested changes
Thanks! Couple of smaller issues inline.

At least optionally, we need to be able to take the cvmfs sources from the build host.  Perhaps this can be done with another Dockerfile argument that would point to a sources directory (or alternatively clone them from github).  If we can take a source tree from the build host, we solve two issues

1. We get the sticky externals back
2. We can build PRs where the sources live in a fork

2020-09-17 09:59 UTC, jblomer commented on packaging/container/Dockerfile
> -LABEL maintainer="jblomer@cern.ch"
We should keep the labels for properness

2020-09-17 09:59 UTC, jblomer commented on packaging/container/Dockerfile
>  ENV CVMFS_HTTP_PROXY=
Let's add `CVMFS_CLIENT_PROFILE` from https://github.com/cvmfs/cvmfs/pull/2603/files

2020-09-17 09:59 UTC, jblomer commented on ci/cvmfs/container.sh
> -  ${CVMFS_SOURCE_LOCATION} ${CVMFS_RESULT_LOCATION} ${CVMFS_BUSYBOX} ${CVMFS_TAG} \
I think we want both the `CVMFS_TAG` and the `git_hash`.  The `CVMFS_TAG` provides us a linear version number, which is nice, and the git hash allows us to clone the corresponding sources.

2020-09-17 09:59 UTC, jblomer commented on packaging/container/Dockerfile
> +ARG CVMFS_COMMIT=cvmfs-2.7.4
This should be unset so that we enforce a provided argument.  Otherwise we might get "silently" the wrong version built.

2020-09-17 09:59 UTC, jblomer commented on packaging/container/Dockerfile
> +        rm -rf ~/root/usr/lib*/libcvmfs_fuse.* \
`rm -rf` --> `rm -f`

2020-09-17 09:59 UTC, jblomer commented on packaging/container/Dockerfile
> +        rm -rf ~/root/usr/lib*/libcvmfs_fuse.* \
The mount helper should be removed, too

2020-09-17 09:59 UTC, jblomer commented on packaging/container/build.sh
> -  -DEXTERNALS_PREFIX=${CVMFS_RESULT_LOCATION}/externals \
That's of course a pity that we have to give it up.  Now when we want to debug building the container, we always have to build the full cvmfs including the externals.  Previously, the external builds could stick around and we did not need to rebuild them. Hm, any ideas?

2020-09-17 09:59 UTC, jblomer commented on packaging/container/Dockerfile
> +        rm -rf ~/root/usr/lib*/libcvmfs_fuse.* \
The `cvmfs_config` script should be removed, too

2020-09-17 09:59 UTC, jblomer commented on packaging/container/Dockerfile
> +ARG BUSYBOX_URL=https://ecsft.cern.ch/dist/cvmfs/builddeps/busybox
Let's leave that empty, too

2020-09-17 09:59 UTC, jblomer commented on packaging/container/Dockerfile
> +RUN mkdir -p /var/log /var/run/cvmfs
The container config is missing

2020-09-17 09:59 UTC, jblomer commented on packaging/container/build.sh
> -docker inspect $IMAGE_NAME
That provided at some point helpful debugging output

2020-09-23 08:10 UTC, siscia commented
We should restructure this as a build step not a packaging one.

The packaging step should follow and generate the tar from the docker container.

2020-09-23 08:10 UTC, closed without merging