CVM-1972 Get root hash from extended attributes when setting the publisher
cvmfs/cvmfs pull request #2679
Opened 2021-02-22 15:18 UTC by aandvalenzuela

2021-02-23 07:52 UTC, aandvalenzuela commented
@cernvm-bot cloudtest

2021-02-25 15:26 UTC, aandvalenzuela commented
@cernvm-bot cloudtest

2021-03-01 11:37 UTC, aandvalenzuela commented
@cernvm-bot cloudtest

2021-03-01 17:39 UTC, jblomer commented
Test 536 seems to fail with the patch

2021-03-02 09:08 UTC, jblomer commented on cvmfs/publish/settings.cc
> +    throw EPublish("cannot get extrended attribute root_hash");
```suggestion
    throw EPublish("cannot get extended attribute root_hash");
```

2021-03-02 17:13 UTC, aandvalenzuela commented
@cernvm-bot cloudtest

2021-03-03 14:47 UTC, jblomer requested changes
Thanks!  I think that catching the error is yet at the wrong level.

If we ask for the root hash inside the enter shell, we do expect `GetRootHashXAttr` to succeed. Only for the managed publisher, we can ignore the error.

So `GetRootHashXAttr` should still throw an exception, which is (only) caught and ignored in the lower part of `CreateSettingsPublisher`

2021-03-04 14:37 UTC, aandvalenzuela commented
@cernvm-bot cloudtest

2021-03-05 09:12 UTC, aandvalenzuela commented
@cernvm-bot cloudtest

2021-03-05 09:17 UTC, aandvalenzuela commented
@cernvm-bot cloudtest cc7

2021-03-05 14:39 UTC, aandvalenzuela commented
@cernvm-bot cloudtest cc7

2021-03-05 14:45 UTC, aandvalenzuela commented
@cernvm-bot cloudtest cc7

2021-03-05 14:47 UTC, aandvalenzuela commented
@cernvm-bot cloudtest cc7

2021-03-05 16:05 UTC, aandvalenzuela commented
@cernvm-bot cloudtest

2021-03-08 18:32 UTC, aandvalenzuela commented
@cernvm-bot cloudtest cc7

2021-03-08 19:59 UTC, aandvalenzuela commented
@cernvm-bot cloudtest

2021-03-08 20:02 UTC, aandvalenzuela commented
@cernvm-bot cloudtest

2021-03-08 20:03 UTC, aandvalenzuela commented
@cernvm-bot cloudtest full

2021-03-08 20:03 UTC, aandvalenzuela commented
@cernvm-bot cloudtest

2021-03-08 21:05 UTC, jblomer approved these changes
Looks good to me!

2021-03-08 21:05 UTC, jblomer commented on test/src/683-diffworktree/main
> +}
The trailing newline is missing

2021-03-09 09:23 UTC, merged