Log issue of template transaction in an existing directory correctly
cvmfs/cvmfs pull request #2691
Opened 2021-03-19 10:37 UTC by aandvalenzuela

2021-03-19 10:38 UTC, aandvalenzuela commented
@cernvm-bot cloudtest

2021-03-19 13:28 UTC, jblomer requested changes
Very nice

2021-03-19 13:28 UTC, jblomer commented on cvmfs/publish/repository_transaction.cc
> +      LogCvmfs(kLogCvmfs, kLogStdout, "%s", e.what());
Rather than logging the error here, let's append it to the `EPublish` exception.

2021-03-19 13:28 UTC, jblomer commented on cvmfs/publish/cmd_transaction.cc
> +      LogCvmfs(kLogCvmfs, kLogStderr | kLogSyslogErr, "%s%s",
Good catch!

2021-03-19 13:28 UTC, jblomer commented on cvmfs/publish/cmd_transaction.cc
> +      throw;
Let's instead return `EINVAL`

2021-03-19 13:28 UTC, jblomer commented on cvmfs/publish/cmd_transaction.cc
> +      LogCvmfs(kLogCvmfs, kLogStderr | kLogSyslogErr, "%s",
Like in the other cases, the error message of the exception should be logged, too

2021-03-19 16:36 UTC, aandvalenzuela commented
@cernvm-bot cloudtest

2021-03-20 20:00 UTC, jblomer approved these changes

2021-03-22 08:24 UTC, merged