Webhook integration test
cvmfs/cvmfs pull request #2716
Opened 2021-05-26 12:48 UTC by aandvalenzuela

2021-06-15 09:13 UTC, jblomer requested changes
Very good! A few comments inline

2021-06-15 09:13 UTC, jblomer commented on test/src/406-ducc-webhook-notifications/main
> +
Remove empty line

2021-06-15 09:13 UTC, jblomer commented on test/src/406-ducc-webhook-notifications/main
> +    sudo python3 /root/cvmfs/test/src/406-ducc-webhook-notifications/registry-webhook.py -f $notifications_file -h 188.185.120.234 -p 8080 &
Are you sure this needs to run as `sudo`?

2021-06-15 09:13 UTC, jblomer commented on test/src/406-ducc-webhook-notifications/main
> +    yes | touch $notifications_file
This should work without a confirmation, I'd think

2021-06-15 09:13 UTC, jblomer commented on test/src/406-ducc-webhook-notifications/main
> +    sleep 1
Does the test work without sleep? Sleeping is likely to make the test flaky.

2021-06-15 09:13 UTC, jblomer commented on test/src/406-ducc-webhook-notifications/main
> +    curl -X POST http://webhook-c8vm:8080/webhooks/test-cvmfs-ingestion -H "Content-Type: application/json" -d "{\"type\": \"PUSH_ARTIFACT\", \"event_data\": {\"resources\": [{\"resource_url\": \"reg
```suggestion
    curl -X POST http://localhost:8080/webhooks/test-cvmfs-ingestion -H "Content-Type: application/json" -d "{\"type\": \"PUSH_ARTIFACT\", \"event_data\": {\"resources\": [{\"resource_url\": \"registry.cern.ch/unpacked-dev/image:tag\"}]}}" || return 3
```

2021-06-15 09:13 UTC, jblomer commented on test/src/406-ducc-webhook-notifications/main
> +    curl -X POST http://webhook-c8vm:8080/webhooks/test-cvmfs-ingestion -H "Content-Type: application/json" -d "{\"type\": \"DELETE_ARTIFACT\", \"event_data\": {\"resources\": [{\"resource_url\": \"r
```suggestion
    curl -X POST http://localhost:8080/webhooks/test-cvmfs-ingestion -H "Content-Type: application/json" -d "{\"type\": \"DELETE_ARTIFACT\", \"event_data\": {\"resources\": [{\"resource_url\": \"registry.cern.ch/unpacked-dev/image:tag\"}]}}" || return 4
```

2021-06-15 09:13 UTC, jblomer commented on test/src/406-ducc-webhook-notifications/main
> +    curl -X POST http://webhook-c8vm:8080/webhooks/test-cvmfs-ingestion -H "Content-Type: application/json" -d "{\"type\": \"REPLICATION\", \"event_data\": {\"replication\": { \"dest_resource\": {\"e
```suggestion
    curl -X POST http://localhost:8080/webhooks/test-cvmfs-ingestion -H "Content-Type: application/json" -d "{\"type\": \"REPLICATION\", \"event_data\": {\"replication\": { \"dest_resource\": {\"endpoint\": \"https://registry.cern.ch\", \"namespace\": \"unpacked-dev\"}, \"successful_artifact\": [{\"type\": \"image\", \"status\": \"Success\", \"name_tag\": \"image:tag\"}]}}}" || return 5
```

2021-06-15 09:13 UTC, jblomer commented on test/src/406-ducc-webhook-notifications/main
> +        kill $pid
Let's use a `trap` to stop the webhook.  You can search for `trap` in other integration tests and use it as a template

2021-06-15 09:13 UTC, jblomer commented on test/src/406-ducc-webhook-notifications/main
> +    sleep 1
Let's try to remove the sleep

2021-06-15 09:13 UTC, jblomer commented on test/src/406-ducc-webhook-notifications/main
> +    original_content=$(<$notifications_file)
Might be easier to just copy the file to a temporary one and than use `diff` to compare with the rotated.

2021-07-08 09:42 UTC, aandvalenzuela commented
@cernvm-bot cloudtest

2021-08-11 13:06 UTC, aandvalenzuela commented
I close this PR to continue in [#2770](https://github.com/cvmfs/cvmfs/pull/2770).

2021-08-11 13:06 UTC, closed without merging