Webhook: registry application
cvmfs/cvmfs pull request #2723
Opened 2021-06-04 17:52 UTC by aandvalenzuela

2021-06-04 17:53 UTC, aandvalenzuela commented
@cernvm-bot cloudtest

2021-06-09 13:15 UTC, aandvalenzuela commented
@cernvm-bot cloudtest

2021-06-14 12:23 UTC, jblomer requested changes
Very nice!

2021-06-14 12:23 UTC, jblomer commented on ducc/webhook/README.md
> +python3 registry-webhook.py -f "notifications.txt" -h 188.185.120.234 -p 8080
Let's not use real IP addresses in the documentation

```suggestion
python3 registry-webhook.py -f "notifications.txt" -h 127.0.0.1 -p 8080
```

2021-06-14 12:23 UTC, jblomer commented on ducc/webhook/README.md
> +* `--host`(`-h'): name of the server.
```suggestion
* `--host`(`-h'): IP address of the interface to bind to.
```

2021-06-14 12:23 UTC, jblomer commented on ducc/webhook/registry-webhook.py
> +
Let's remove the empty line

2021-06-14 12:23 UTC, jblomer commented on ducc/webhook/registry-webhook.py
> +            print("The replicated artifact already exists")
Let's print out which artifact exists

2021-06-14 12:23 UTC, jblomer commented on ducc/webhook/registry-webhook.py
> +            if (int(last_line_id) % 1000 == 0 and int(last_line_id) != 0):
The `1000` should become a command line parameter. We need it small for testing, and large for production.

2021-06-14 12:23 UTC, jblomer commented on ducc/webhook/registry-webhook.py
> +                new_notifications_file = notifications_file.replace('.txt','')+str(last_line_id)+'.txt'
Let's rename the file into a <from id>-<to id> file name

2021-06-14 12:23 UTC, jblomer commented on ducc/webhook/registry-webhook.py
> +                    f.write(f'--- FILE ROTATION ---\n')
This could have the same format than all the other lines, just with a special action id

2021-06-14 12:23 UTC, jblomer commented on ducc/webhook/registry-webhook.py
> +        message = f'{action}|{image}'
We don't want or need to write into the notifications file here, do we?

2021-06-21 14:50 UTC, aandvalenzuela commented
@cernvm-bot cloudtest

2021-06-24 08:22 UTC, jblomer approved these changes

2021-06-24 08:22 UTC, merged