Introduce bundles content type in the repository
cvmfs/cvmfs pull request #2741
Opened 2021-06-25 12:43 UTC by RohitTopi

2021-06-29 08:50 UTC, jblomer requested changes
Let's add to this one the header file and a skeleton for the unit test. Let's also add the files to the CMakeLists.txt file.

2021-06-29 08:50 UTC, jblomer commented on cvmfs/bundle.cc
> +
Let's add least add the usual cvmfs comment header.

2021-07-05 14:46 UTC, jblomer requested changes
It's taking shape!  You can actually add unit tests for `CreateBundle` right away.

2021-07-05 14:46 UTC, jblomer commented on cvmfs/bundle.cc
> +ObjectPack* Bundle::CreateBundle(const JSON* json_obj)
Style: 

```suggestion
ObjectPack *Bundle::CreateBundle(const JSON *json_obj) {
```

2021-07-05 14:46 UTC, jblomer commented on cvmfs/bundle.h
> + * A bundle has the binary format of object packs used by the gateway as
```suggestion
 * A bundle has the binary format of object packs used as
```

2021-07-05 14:46 UTC, jblomer commented on cvmfs/bundle.h
> + *
Let's document the JSON structure that `CreateBundle` expects

2021-07-05 14:46 UTC, jblomer commented on cvmfs/bundle.h
> +  ObjectPack* CreateBundle(const JSON* json_obj);
```suggestion
  ObjectPack *CreateBundle(const JSON *json_obj);
```

2021-07-05 14:46 UTC, jblomer commented on cvmfs/bundle.cc
> +    ObjectPack* op = new ObjectPack();
Let's use a `UniquePtr` from pointer.cc. We then don't need the explicit `delete` calls in the error paths. We return it with `UniquePtr::Release()`

2021-07-05 14:46 UTC, jblomer commented on cvmfs/bundle.cc
> +        PrintWarning("File not found: " + filepath);
We should decide here: either warn and skip (instead of returning) or we `PANIC`. I think we want to warn and skip.

2021-07-05 14:46 UTC, jblomer commented on cvmfs/bundle.cc
> +    if (value->first_child) {
Combine with while loop further down to remove the code duplication.

2021-07-05 14:46 UTC, jblomer commented on cvmfs/bundle.cc
> +    } else {
Let's error out early if an empty bundle is found.

2026-05-20 12:19 UTC, vvolkl commented
Superseded by #4002

2026-05-20 12:19 UTC, closed without merging