Fix import s3
cvmfs/cvmfs pull request #2777
Opened 2021-09-01 09:32 UTC by hmeiland

renewing pull request for fixing import of s3 backed cvmfs (closing old one due to merge conflicts)

2021-09-01 09:33 UTC, hmeiland commented
test with azurite not possible at this moment: azurite crashes on import, while azure blob handles correctly.

2021-09-05 15:58 UTC, jblomer commented
Many thanks! Do you know why azurite crashes?

2021-09-06 12:22 UTC, hmeiland commented
had to merge azureblob into this one to get all the changes working; now the azurite works for import as well...
need to discuss on removal of assert in signing_tool...

2021-09-06 12:22 UTC, hmeiland commented
> Many thanks! Do you know why azurite crashes?

yes -> was not pointing to the correct tcp port no... ;( ,fixed now

2021-09-20 17:14 UTC, jblomer requested changes
Many thanks!  Import with S3 would be a great new functionality!  Let's merge #2776 first and rebase this on on top. On the reflog checksum, are you sure that removing the assert is necessary, i.e. does importing break otherwise, and where?

2021-09-20 17:14 UTC, jblomer commented on cvmfs/server/cvmfs_server_import.sh
> +  if [ x"$(is_local_upstream $upstream)" != "x" ]; then
```suggestion
  if is_local_upstream $upstream; then
```

2021-09-28 14:18 UTC, hmeiland commented
> Many thanks! Import with S3 would be a great new functionality! Let's merge #2776 first and rebase this on on top. On the reflog checksum, are you sure that removing the assert is necessary, i.e. does importing break otherwise, and where?

Yes, the assert is clearly the one breaking the import; I can not find another way to satisfy the assert condition; If you feel there should be, let's set up a short call to discuss...

2021-10-04 12:05 UTC, jblomer commented
@cernvm-bot help

2021-10-05 06:23 UTC, jblomer commented
@cernvm-bot cloudtest

2021-10-05 06:24 UTC, jblomer commented
@cernvm-bot unittest

2021-10-05 06:24 UTC, jblomer commented
@cernvm-bot cpplint

2021-10-05 06:24 UTC, jblomer commented
@cernvm-bot tidy

2021-10-12 11:52 UTC, jblomer commented
The change in the reflog checksum handling looks fine to me. The PR is replaced by #2795 which contains some additional fixes.

2021-10-12 11:52 UTC, closed without merging