cvmfs_receiver performance: remove ShortString counters
cvmfs/cvmfs pull request #2903
Opened 2022-04-25 09:34 UTC by mharvey-jt

In profiling the commit processor critical path, we observed that a substantial amount of time in `AbstractCatalogManager::MountSubtree`->`ShortString::ShortString`.  Approx half of the time spent in this constructor is in the atomic_inc64() of `num_instances_`.

In our environment, we don't use the `num_instances` or `num_overflows` statistics for `ShortString` derived objects, so this PR removes them.

It might, perhaps, be more elegant to make these counters configurable, so they can be disabled only where required.

```
12.68% 0.76% cvmfs_receiver cvmfs_receiver
11.93% catalog::AbstractCatalogManager<catalog: : Catalog>: :MountSubtree
- 6.31% ShortString<(unsigned char)200, (char)0>::ShortString 2.53% ShortString<(unsigned char) 200, (char)0>:: Assign 2.44% atomic_inc64
0.59% ShortString<(unsigned char)200, (char)0>::GetLength
2.64% ShortString<(unsigned char) 200, (char)0>:: Append
1.11% ShortString<(unsigned char)200, (char)0>::GetLength
1.01% ShortString<(unsigned char)200, (char)0>:: StartsWith
+0.76% libc_start_main
[.] catalog::AbstractCatalogManager<catalog::Catalog>:: MountSubtree
```

2022-04-25 09:50 UTC, radupopescu commented
@cernvm-bot tidy

2022-04-25 09:50 UTC, radupopescu commented
@cernvm-bot cpplint

2022-04-25 09:50 UTC, radupopescu commented
@cernvm-bot unittest

2022-04-25 09:56 UTC, radupopescu commented
Thanks for the patch!

2022-04-25 10:05 UTC, jblomer requested changes
Thanks for the profiling info!  That is super useful!

The counters are not relevant for the server side, so we can certainly restrict them to the client.  Probably even to the debug build of the client only.  There are useful to check if the stack allocations still match the majority of path/name lengths.

2022-04-25 19:37 UTC, mharvey-jt commented
Is there a convenient set of preprocessor #defines indicating whether the build is client, server, and debug ?

2022-10-12 11:48 UTC, HereThereBeDragons commented
#3081 s a replacement for this

2022-10-14 21:37 UTC, jblomer commented
Closing in favor of #3081

2022-10-14 21:37 UTC, closed without merging