commitprocessor performance: truncate instead of re-initializing PathString in DiffRec
cvmfs/cvmfs pull request #2904
Opened 2022-04-25 09:42 UTC by mharvey-jt

The DiffRec function is the main function to compare the new and old catalogs. Inside this function, it compares the old and new entry and create PathStrings in each iteration of the loop. This is quite inefficient because each time it does a memcpy (ShortString::Assign) to initialize old_path and new_path from path. This gets worse as you traverse down the directory tree because the path gets longer.

This PR adds a Truncate function to ShortString which allows us to simply reduce the length of old_path and new_path and append the entry name, instead of re-initializing it from path.

2022-04-25 09:53 UTC, radupopescu commented
@cernvm-bot unittest

2022-04-25 09:53 UTC, radupopescu commented
@cernvm-bot cpplint

2022-04-25 09:53 UTC, radupopescu commented
@cernvm-bot tidy

2022-04-25 09:56 UTC, radupopescu commented
Thanks for the patch!

2022-11-11 16:37 UTC, jblomer requested changes
Essentially good to go, just some minor issues.

2022-11-11 16:37 UTC, jblomer commented on cvmfs/shortstring.h
> +  void Truncate(unsigned char new_length) {
```suggestion
  void Truncate(unsigned new_length) {
```

It seems unnecessary to restrict `new_length` to 255 characters.

2022-11-11 16:37 UTC, jblomer commented on cvmfs/shortstring.h
> +    if (long_string_) {
We should add a method documentation that the use of `Truncate()` can lead to a heap allocated string that is shorter than the reserved stack space.

2022-11-11 16:37 UTC, jblomer commented on cvmfs/catalog_diff_tool_impl.h
> +  unsigned char length_after_truncate = old_path.GetLength();
```suggestion
  unsigned length_after_truncate = old_path.GetLength();
```

2022-11-25 15:38 UTC, HereThereBeDragons commented
#3116 has the requested changes

2022-11-27 15:31 UTC, merged