commitprocessor performance: avoid unnecessary construction of ShortString in MountSubtree
cvmfs/cvmfs pull request #2906
Opened 2022-04-25 09:54 UTC by mharvey-jt

Rewrite logic to avoid construction of a ShortString, reducing time spent in critical path
```
-   11.17%     1.00%  cvmfs_receiver  cvmfs_receiver       [.] catalog::AbstractCatalogManager<catalog::Catalog>::MountSubtree
   - 10.16% catalog::AbstractCatalogManager<catalog::Catalog>::MountSubtree
      + 5.69% ShortString<(unsigned char)200, (char)0>::ShortString
      + 2.78% ShortString<(unsigned char)200, (char)0>::Append
        1.09% ShortString<(unsigned char)200, (char)0>::StartsWith
   + 1.00% CatalogDiffTool<catalog::SimpleCatalogManager>::DiffRec
```

2022-04-25 09:55 UTC, radupopescu commented
@cernvm-bot unittest

2022-04-25 09:55 UTC, radupopescu commented
@cernvm-bot cpplint

2022-04-25 09:55 UTC, radupopescu commented
@cernvm-bot tidy

2022-04-25 09:56 UTC, radupopescu commented
Thanks for the patch!

2022-10-16 20:35 UTC, jblomer commented
@cernvm-bot tidy

2022-10-16 20:35 UTC, jblomer commented
@cernvm-bot cpplint

2022-10-16 20:35 UTC, jblomer commented
@cernvm-bot unittest

2022-10-16 20:39 UTC, jblomer commented
@cernvm-bot cloudtest

2022-10-16 20:59 UTC, jblomer requested changes
Many thanks! Looks in principle good to me. Some minor comments and linter failures.

2022-10-16 20:59 UTC, jblomer commented on cvmfs/catalog_mgr_impl.h
> +      mountpoint_len = i->mountpoint.GetLength();
Let's declare `mountpoint_len` here instead of the beginning of the method

2022-10-16 20:59 UTC, jblomer commented on cvmfs/catalog_mgr_impl.h
> +      // checking it this way allows us to avoid the
I think this last sentence of the comment is not clear without seeing the diff with the previous version of the code. Let's remove it.

2022-10-17 09:06 UTC, jblomer commented
@cernvm-bot cloudtest

2022-10-17 11:14 UTC, jblomer commented
Integration test failures are unrelated.

2022-11-07 22:36 UTC, mharvey-jt commented on cvmfs/catalog_mgr_impl.h
> +      mountpoint_len = i->mountpoint.GetLength();
changed as requested

2022-11-07 22:36 UTC, mharvey-jt commented on cvmfs/catalog_mgr_impl.h
> +      // checking it this way allows us to avoid the
changed as requested

2022-11-08 13:21 UTC, jblomer commented
@cernvm-bot cloudtest

2022-11-08 13:21 UTC, jblomer commented
@cernvm-bot cpplint

2022-11-08 13:21 UTC, jblomer commented
@cernvm-bot tidy

2022-11-08 13:22 UTC, jblomer commented
@cernvm-bot unittest

2022-11-08 13:24 UTC, jblomer approved these changes

2022-11-09 13:34 UTC, merged