handle CURLE_SEND_ERROR
cvmfs/cvmfs pull request #2925
Opened 2022-04-25 15:59 UTC by mharvey-jt

The curl error CURLE_SEND_ERROR can be seen when a cache is misbehaving, and closing connections before the http request send is completed.
Handle this error, treating it as a short transfer error.

2022-10-16 20:14 UTC, jblomer commented
@cernvm-bot cpplint

2022-10-16 20:14 UTC, jblomer commented
@cernvm-bot tidy

2022-10-16 20:14 UTC, jblomer commented
@cernvm-bot unittest

2022-10-16 20:14 UTC, jblomer commented
@cernvm-bot cloudtest

2022-10-16 20:15 UTC, jblomer requested changes
Many thanks! Looks good to me! Let's just add the explanation in the PR as a code comment.

2022-10-17 09:05 UTC, jblomer commented
@cernvm-bot cloudtest

2022-10-17 11:11 UTC, jblomer commented
Integration test failures are unrelated.

2022-11-07 20:57 UTC, mharvey-jt commented
Comment added as requested

2022-11-08 09:28 UTC, merged