Add CVMFS_WORLD_READABLE to make repo contents globally readable
cvmfs/cvmfs pull request #3012
Opened 2022-08-04 13:23 UTC by mharvey-jt

We have a use case for which it is desirable to override the posix permissions encoded in the repo, and make all files globally readable. This patch adds the binary configuration option `CVMFS_WORLD_READABLE` to enable this. It is patterned after `CVMFS_CLAIM_OWNERSHIP` which it is used in conjunction with.

2022-08-04 13:53 UTC, radupopescu commented
Thanks for the patch!

2022-08-04 13:53 UTC, radupopescu commented
@cernvm-bot tidy

2022-08-04 13:53 UTC, radupopescu commented
@cernvm-bot cpplint

2022-08-04 13:53 UTC, radupopescu commented
@cernvm-bot unittests

2022-08-04 13:59 UTC, radupopescu commented
@cernvm-bot unittest

2022-08-23 08:57 UTC, jblomer commented
That looks useful!  We'll add an integration test and probably reopen the PR.

2022-10-16 20:50 UTC, jblomer requested changes
Perhaps you could help us with the linter errors and a small integration test. The code itself I think is ready to be merged.

2022-10-17 09:05 UTC, jblomer commented
@cernvm-bot unittest

2022-11-07 21:41 UTC, mharvey-jt commented
@cernvm-bot cpplint

2022-11-08 09:51 UTC, jblomer commented
@cernvm-bot cpplint

2022-11-08 09:51 UTC, jblomer commented
@cernvm-bot tidy

2022-11-08 09:52 UTC, jblomer requested changes
Looks good to me, let's just add an integration test.

2022-11-10 19:47 UTC, mharvey-jt commented
@jblomer Added Laura's test

2022-11-16 12:29 UTC, jblomer requested changes
Looks good to me, just some trimming on the integration test.

2022-11-16 12:29 UTC, jblomer commented on test/src/704-world_readable/main
> +}
Missing newline at the end of the file

2022-11-16 12:29 UTC, jblomer commented on test/src/704-world_readable/main
> +  local config_file_path="${scratch_dir}/${CVMFS_TEST_REPO}.config.txt"
I don't think `config_file_path` is used.

2022-11-16 12:29 UTC, jblomer commented on test/src/704-world_readable/main
> +TEST704_PIDS=
Unused, remove

2022-11-16 12:29 UTC, jblomer commented on test/src/704-world_readable/main
> +CVMFS_TEST_704_OSXMOUNTPOINT=
Unused, remove

2022-11-16 12:29 UTC, jblomer commented on test/src/704-world_readable/setup_teardown
> +  if [ "x$TEST704_PIDS" != "x" ]; then
Unused `if` block, remove

2022-11-16 12:29 UTC, jblomer commented on test/src/704-world_readable/setup_teardown
> +}
Missing newline at the end of the file

2022-11-16 12:29 UTC, jblomer commented on test/src/704-world_readable/main
> +# for fuse 2
Comment seems off, remove?

2022-11-16 12:29 UTC, jblomer commented on test/src/704-world_readable/main
> +
Remove one of the two empty lines

2022-11-16 12:29 UTC, jblomer commented on test/src/704-world_readable/main
> +  ls -ld $mntpnt/test1.txt  | grep -qe ^-r--r--r--
```suggestion
  ls -ld $mntpnt/test1.txt | grep -qe ^-r--r--r--
```

2022-11-16 12:29 UTC, jblomer commented on test/src/704-world_readable/main
> +  ls -ld $mntpnt/testdir  | grep -qe ^dr-xr-xr-x
```suggestion
  ls -ld $mntpnt/testdir | grep -qe ^dr-xr-xr-x
```

2022-11-16 12:29 UTC, jblomer commented on test/src/704-world_readable/main
> +  ls -ld $mntpnt/testdir/test2.txt  | grep -qe ^-r--r--r--
```suggestion
  ls -ld $mntpnt/testdir/test2.txt | grep -qe ^-r--r--r--
```

2022-11-16 12:29 UTC, jblomer commented on test/src/704-world_readable/main
> +
Remove one of the two empty lines

2022-11-16 12:29 UTC, jblomer commented on test/src/704-world_readable/setup_teardown
> +# add_some_tmp_file_to_repo() {
Remove commented code

2022-11-16 12:29 UTC, jblomer commented on test/src/704-world_readable/setup_teardown
> +  local fuse_version="$2"
Unused, remove

2022-11-16 12:29 UTC, jblomer commented on test/src/704-world_readable/setup_teardown
> +  local config_file_path="$3"
Unused, remove

2022-11-16 12:29 UTC, jblomer commented on test/src/704-world_readable/setup_teardown
> +  local mount_options="rw,system_mount,fsname=cvmfs2"
Should not be required, try removing

2022-11-16 12:29 UTC, jblomer commented on test/src/704-world_readable/setup_teardown
> +  local fuse_version="$2"
Unused, remove

2022-11-16 12:29 UTC, jblomer commented on test/src/704-world_readable/setup_teardown
> +  local config_file_path="$3"
Unused, remove

2022-11-16 12:29 UTC, jblomer commented on test/src/704-world_readable/setup_teardown
> +  local mount_options="rw,system_mount,fsname=cvmfs2"
Should not be possible, remove

2022-11-16 12:29 UTC, jblomer commented on test/src/704-world_readable/setup_teardown
> +CVMFS_SYSLOG_LEVEL=2" \
Can this be removed?

2022-11-16 12:29 UTC, jblomer commented on test/src/704-world_readable/setup_teardown
> +CVMFS_SYSLOG_LEVEL=2" \
Can this be removed?

2022-11-16 12:29 UTC, jblomer commented on test/src/704-world_readable/setup_teardown
> +private_mount_world_readable() {
This function as well as the `private_mount_not_world_readable` don't seem to add much. Consider using `do_local_mount_as_root` directly or at least merging the tow functions into one.

2022-11-24 15:11 UTC, HereThereBeDragons commented on test/src/704-world_readable/main
> +TEST704_PIDS=
not true. its used in `setup_teardown`

2022-11-24 16:35 UTC, HereThereBeDragons commented
replaced by #3115 which contains the cleanup of the test

2022-11-24 20:17 UTC, closed without merging