Fix compile error "'time' was not declared in this scope"
cvmfs/cvmfs pull request #3046
Opened 2022-09-02 08:18 UTC by fsiegert

In Archlinux with gcc 12.2.0 we see a compilation error that seems to come from a missing `<ctime>` include. More details can be found in https://aur.archlinux.org/packages/cvmfs#comment-879961.

This PR fixes the issue.

2022-09-02 16:04 UTC, jblomer requested changes
Many thanks for the patch!

Please just move the include down below `#include <cstring>`

2022-09-04 12:04 UTC, fsiegert commented
Thanks @jblomer, this is indeed more tidy and I have amended the commit. Hope it's fine now!

2022-09-04 20:10 UTC, jblomer commented
@cernvm-bot unittest

2022-09-04 20:10 UTC, jblomer commented
@cernvm-bot cpplint

2022-09-04 20:10 UTC, jblomer approved these changes
Many thanks!

2022-09-04 20:49 UTC, merged