Change LookupOption
cvmfs/cvmfs pull request #3074
Opened 2022-10-04 08:14 UTC by HereThereBeDragons

Related to #3028 
- LookupOption type changes from enum to unsigned to be able to be a bit mask
- `kLookupSole` is renamed to `kLookupDefault` as this is the default treatment of a directory entry
- added some comments about the functionality

2022-10-04 19:47 UTC, jblomer requested changes
Very nice!  One nit, otherwise I'll put this on hold until the 2.10 branch is created, so this will go into 2.11

2022-10-04 19:47 UTC, jblomer commented on cvmfs/catalog_mgr.h
> + * kLookupRawSymlink = Mangle symlink to which the directory entry points to
```suggestion
 * kLookupRawSymlink = Don't resolve environment variables in symlink targets
```

2022-10-06 08:03 UTC, HereThereBeDragons commented
Added your change request

2022-10-06 20:45 UTC, jblomer commented
While this is on hold, could you check the [clang-tidy report](https://lcgapp-services.cern.ch/cvmfs-jenkins/job/CvmfsTidy/label=docker-x86_64/448/console) if it is a false positive or not? It's certainly not related to the patch but it may have still have found something.

2022-10-11 07:53 UTC, HereThereBeDragons commented
Just for the logs: clang-tidy problems will be handled by @jblomer

2022-10-11 22:28 UTC, merged