Add CVMFS_S3_X_AMZ_ACL
cvmfs/cvmfs pull request #3102
Opened 2022-11-11 20:34 UTC by mharvey-jt

Permitted values:
```    "private",
    "public-read",
    "public-write",
    "authenticated-read",
    "aws-exec-read",
    "bucket-owner-read",
    "bucket-owner-full-control",
    ""
```
default is `public-read`

2022-11-11 21:27 UTC, HereThereBeDragons commented
Issue #2970

2022-11-30 22:29 UTC, jblomer commented
@cernvm-bot unittest

2022-11-30 22:29 UTC, jblomer commented
@cernvm-bot cloudtest

2022-12-12 12:46 UTC, jblomer commented
@cernvm-bot unittest

2022-12-12 12:46 UTC, jblomer commented
@cernvm-bot tidy

2022-12-12 12:46 UTC, jblomer commented
@cernvm-bot cpplint

2022-12-12 12:49 UTC, HereThereBeDragons commented
@jblomer there are some typos that prevent building this PR. i fixed it and open a PR on mharvey-jt branch

2022-12-13 09:56 UTC, HereThereBeDragons commented
@cernvm-bot cloudtest

2022-12-14 12:05 UTC, jblomer requested changes
In principal looks good to me!  One nit on the array of allowed values.  We could use test case 684 to test that an unknown value will be rejected. But there isn't that much value in the test.  I guess the per-bucket policy can only be tested against GCS? In this case, let's not bother for the moment.

2022-12-14 12:05 UTC, jblomer commented on cvmfs/upload_s3.h
> +   *  * Allowed values of x-amz-acl according to S3 API
```suggestion
   * Allowed values of x-amz-acl according to S3 API
```

2022-12-14 12:05 UTC, jblomer commented on cvmfs/upload_s3.h
> +   *  */
```suggestion
   **/
```

2022-12-14 12:05 UTC, jblomer commented on cvmfs/upload_s3.h
> +  std::string const  x_amz_acl_allowed_values_[8] = {
Let's make this `static const char *`.

2022-12-14 12:05 UTC, jblomer commented on cvmfs/s3fanout.cc
> +  headers->push_back("X-Amz-Acl: "+config_.x_amz_acl);
```suggestion
  headers->push_back("X-Amz-Acl: " + config_.x_amz_acl);
```

2022-12-20 14:43 UTC, mharvey-jt commented
the most straightforward way to test this would be to have the test harness apache log transaction headers and then confirm the expected ones are present. Is there precedent for that elsewhere in the test suite?

2023-01-13 11:54 UTC, jblomer commented
@cernvm-bot cloudtest

2023-01-13 14:53 UTC, merged