cvmfs/publish: configure curl for https.
cvmfs/cvmfs pull request #3111
Opened 2022-11-20 19:39 UTC by nicolamori

Add the curl_easy_setopt options for setting up a https publisher connection to gateway.

Implements the feature described in #3060. Tested with both http and https gateways under CentOS 7.

2022-11-20 21:16 UTC, jblomer requested changes
Many thanks for getting started with this!

In its current form, the SSL verification is turned off.  You can just leave `CURLOPT_SSL_VERIFYPEER` and `CURLOPT_SSL_VERIFYHOST` options unchanged to make sure the SSL connection is verified.

To load the system certificates, use `SslCertificateStore::UseSystemCertificatePath()` and then use `SslCertificateStore::ApplySslCertificatePath(<curl handle>)`. You can look into download.cc, `ssl_certificate_store_`, for a blueprint.

We unfortunately have not migrated all the code to the new structure yet, so you would also need to change swissknife_lease_curl.cc in a similar fashion.

2022-11-23 11:27 UTC, nicolamori commented
I (hopefully) fixed the code and implemented also for cvmfs_swissknife. I tested `cvmfs_swissknife lease -a acquire/drop` with an https gateway and it worked.

2022-11-23 21:02 UTC, jblomer commented
@cernvm-bot cpplint

2022-11-23 21:02 UTC, jblomer commented
@cernvm-bot tidy

2022-11-23 21:09 UTC, jblomer commented
@cernvm-bot unittest

2022-11-24 20:49 UTC, jblomer approved these changes

2022-11-24 20:49 UTC, jblomer commented
@cernvm-bot cloudtest

2022-11-24 20:50 UTC, jblomer commented
@cernvm-bot cpplint

2022-11-24 20:50 UTC, jblomer commented
@cernvm-bot tidy

2022-11-24 20:50 UTC, jblomer commented
@cernvm-bot unittest

2022-11-25 12:33 UTC, jblomer commented
@cernvm-bot cloudtest

2022-11-25 16:46 UTC, merged