Add CVMFS_CURL_DEBUGLOG to enable Curl transaction tracing
cvmfs/cvmfs pull request #3146
Opened 2022-12-21 15:19 UTC by mharvey-jt

Useful for logging Curl's transactions, can be used to test features that set particular headers.

2022-12-21 16:25 UTC, mharvey-jt commented
@cernvm-bot unittest

2023-03-13 12:40 UTC, jblomer requested changes
In principle looks good to me.  We should just use different files for the different download managers. Otherwise they will double-close the file. Also, `DownloadManager::Clone()` should specifically handle this member (or have a comment that the debug log file won't be cloned).

2023-07-14 13:21 UTC, jblomer commented
@mharvey-jt looking once more into this: is it important to separate the curl debug log from the cvmfs debug log? Otherwise, we can use `CURLOPT_DEBUGFUNCTION` to emit cvmfs debug log output. The advantage of that is that log messages from different files don't need to be correlated, all is serialized in a single file. The disadvantage is that the one might need to grep for the relevant curl-related lines, and that the curl debugging is coupled to the cvmfs debug mode.

2023-07-17 11:56 UTC, jblomer commented
Replaced by #3329

2023-07-17 11:56 UTC, closed without merging