[GC] delete objects only once
cvmfs/cvmfs pull request #3175
Opened 2023-01-30 12:33 UTC by HereThereBeDragons

Issue #3117 
new hashmap that remembers which hashes are already requested to be deleted and skips them if called again
new counter `duplicate_delete_requests_` to count how many of the requests were skipped

2 questions:
- `// TODO(jblomer): turn current counters into perf::Counters` - ??
- `generate_stats_plots.c` - extend it?

extended test by some super simple lines. not sure if needed?

2023-01-31 15:19 UTC, HereThereBeDragons commented
@cernvm-bot cloudtest

2023-01-31 21:11 UTC, jblomer requested changes
In principle looks good to me but we also need to upgrade existing statistics databases with an older schema version. See `LiveSchemaUpgradeIfNecessary()` for details.

2023-02-01 10:34 UTC, HereThereBeDragons commented
@cernvm-bot cloudtest

2023-02-25 22:34 UTC, jblomer approved these changes

2023-02-25 22:35 UTC, merged