Add options to ignore the cache checks and make the memory threshold configurable
cvmfs/cvmfs pull request #3180
Opened 2023-02-01 11:56 UTC by dvandok

There are two additional configuration options to add to the check_cvmfs script:

1. An option to set the memory threshold instead of the hard-coded default
2. A flag to ignore the cache related checks, mostly for osgstorage.org which doesn't play well with the cache

According to DrDave, the osgstorage.org repos don't expect many cache hits. So the default (non-shared) cache size should be small. This is going to trip up the checks. For these repos we want to ignore the cache checks.

2023-02-05 22:10 UTC, jblomer requested changes
Many thanks!  Looks in principle good to me. Just some nits.

2023-02-05 22:10 UTC, jblomer commented on add-ons/check_cvmfs.sh
> +# Version 1.12a, last modified: 31.01.2023
```suggestion
# Version 1.13, last modified: 31.01.2023
```

2023-02-05 22:10 UTC, jblomer commented on add-ons/check_cvmfs.sh
> +# 1.12a - 31.01.2023
```suggestion
# 1.13 - 31.01.2023
```

2023-02-05 22:10 UTC, jblomer commented on add-ons/check_cvmfs.sh
> +VERSION=1.12a
```suggestion
VERSION=1.13
```

2023-02-05 22:10 UTC, jblomer commented on add-ons/check_cvmfs.sh
> +  if [ $OPT_IGNORE_CACHE = 0 ]; then
```suggestion
  if [ $OPT_IGNORE_CACHE -eq 0 ]; then
```

2023-02-05 22:10 UTC, jblomer commented on add-ons/check_cvmfs.sh
> +  if [ $OPT_IGNORE_CACHE = 0 ]; then
```suggestion
  if [ $OPT_IGNORE_CACHE -eq 0 ]; then
```

2023-02-07 08:23 UTC, dvandok commented
Resolved the nits.

2023-02-07 09:43 UTC, jblomer approved these changes

2023-02-07 09:43 UTC, merged