Add proxy_list and proxy_list_external magic xattrs
cvmfs/cvmfs pull request #3233
Opened 2023-03-08 10:22 UTC by mharvey-jt

2023-03-13 12:36 UTC, jblomer requested changes
LGTM, just some nits and let's amend integration test case 087 with the new attributes.

2023-03-13 12:36 UTC, jblomer commented on cvmfs/magic_xattr.cc
> +  dm->GetProxyInfo(
Doesn't need a line break

2023-03-13 12:36 UTC, jblomer commented on cvmfs/magic_xattr.cc
> +  for (std::vector<vector<download::DownloadManager::ProxyInfo>>::iterator
That's fine but wouldn't it be easier to use an integer and iterate from zero to `vector::size()`?

2023-03-14 12:38 UTC, mharvey-jt commented
@cernvm-bot unittest

2023-03-14 12:39 UTC, mharvey-jt commented
@cernvm-bot unittest linux

2023-03-14 12:39 UTC, mharvey-jt commented on cvmfs/magic_xattr.cc
> +  for (std::vector<vector<download::DownloadManager::ProxyInfo>>::iterator
simplified

2023-03-14 12:39 UTC, mharvey-jt commented on cvmfs/magic_xattr.cc
> +  dm->GetProxyInfo(
fixed

2023-03-14 12:39 UTC, mharvey-jt commented
added simple check in 087

2023-03-14 13:45 UTC, mharvey-jt commented
@cernvm-bot codespell

2023-03-20 21:35 UTC, jblomer commented
@cernvm-bot cloudtest

2023-03-20 21:38 UTC, jblomer approved these changes

2023-03-23 14:36 UTC, mharvey-jt commented
@cernvm-bot cloudtest

2023-03-23 21:14 UTC, mharvey-jt commented
@cernvm-bot cloudtest

2023-03-23 21:35 UTC, jblomer commented
@cernvm-bot cloudtest

2023-03-23 23:54 UTC, mharvey-jt commented
@cernvm-bot cloudtest

2023-03-24 00:03 UTC, mharvey-jt commented
@cernvm-bot cloudtest all

2023-03-24 10:56 UTC, vvolkl approved these changes

2023-03-24 10:57 UTC, merged