Don't assert on memory allocation failure
cvmfs/cvmfs pull request #3244
Opened 2023-03-23 12:55 UTC by mharvey-jt

(as discussed offline - finally validated in production)

If CVMFS_SUPPRESS_ASSERTS is defined, keep retrying memory allocation/map failures on failure. This lets CVMFS ride out temporary OOM situations.

Steps to repro:
1) Start with a version of CVMFS that can survive the loss of the the monitor process
2) make a trivial program to consume memory: 
```
 #include <string.h>
#include <stdlib.h>

void main(void) {
for(;;) {
 void *buf = malloc(1024*1024*1024);
 if(buf) { memset(buf, 0, 1024*1024*1024);}
}
}
```
3) mount a repo, and run several concurrent `find /cvmfs/repo ` over it
4) run many copies of the memory hog
5) Wait for the machine to start ooming
6) Observe the cvmfs mount will eventually abort, from one of the assert  in alloc/mmap functions in `smalloc.h`

Retry with this patch in place. Note that the mount process is much more resilient throughout the OOMs.

2023-05-19 13:21 UTC, HereThereBeDragons commented
@cernvm-bot cloudtest

2023-05-31 11:38 UTC, jblomer requested changes
LGTM, except for handling of `size == 0`.

2023-05-31 11:38 UTC, jblomer commented on cvmfs/util/smalloc.h
> +  } while (mem == NULL);
```suggestion
  } while ((size > 0) && (mem == NULL));
```

2023-05-31 11:38 UTC, jblomer commented on cvmfs/util/smalloc.h
> +  } while (mem == NULL);
```suggestion
  } while ((size > 0) && (mem == NULL));
```

2023-05-31 11:38 UTC, jblomer commented on cvmfs/util/smalloc.h
> +  } while (mem == NULL);
```suggestion
  } while ((count * size > 0) && (mem == NULL));
```

2023-05-31 11:57 UTC, mharvey-jt commented on cvmfs/util/smalloc.h
> +  } while (mem == NULL);
changed as suggested

2023-05-31 11:57 UTC, mharvey-jt commented on cvmfs/util/smalloc.h
> +  } while (mem == NULL);
ditto

2023-05-31 11:57 UTC, mharvey-jt commented on cvmfs/util/smalloc.h
> +  } while (mem == NULL);
ditto

2023-05-31 12:02 UTC, jblomer approved these changes

2023-06-01 08:50 UTC, vvolkl approved these changes

2023-06-01 08:50 UTC, merged