platform_filedes_on_tmpfs
cvmfs/cvmfs pull request #3254
Opened 2023-04-05 15:19 UTC by HereThereBeDragons

Replaces #3250 

Ref https://github.com/cvmfs/cvmfs/issues/3192 point 2

2023-04-05 15:20 UTC, HereThereBeDragons commented
@cernvm-bot cloudtest

2023-04-05 15:41 UTC, HereThereBeDragons commented
@cernvm-bot cloudtest

2023-04-06 07:22 UTC, HereThereBeDragons commented
@cernvm-bot help

2023-04-06 07:23 UTC, HereThereBeDragons commented
@cernvm-bot unittest

2023-04-12 12:45 UTC, HereThereBeDragons commented
@cernvm-bot cloudtest

2023-04-17 07:00 UTC, jblomer requested changes
I realize we already have the functionality of `platform_filedes_on_tmpfs` in `GetFileSystemInfo()`. So please use that one. Also, let's set a flag for "no readahead" in `PosixCacheManager::Create`, like we do for other workarounds for caches on special file systems. This avoids having to call `statfs` on every readahead attempt.

2023-04-17 07:00 UTC, jblomer commented on cvmfs/cache_posix.cc
> +  // no-op if fd is on tmpfs
I think it's clear enough here, I'd suggest to remove the comment

2023-04-21 12:40 UTC, HereThereBeDragons commented
Superseded by #3262

2023-04-21 12:40 UTC, closed without merging