Version 2: Reset signals in Authz helper
cvmfs/cvmfs pull request #3261
Opened 2023-04-21 11:47 UTC by HereThereBeDragons

Issue https://github.com/cvmfs/cvmfs/issues/3211

Supersedes https://github.com/cvmfs/cvmfs/pull/3256

Same as PR #3260, just wrong branch name... and did not know that renaming a branch on your fork just closes the PR... (no warning or mentioning was given)

2023-04-21 14:28 UTC, HereThereBeDragons commented
@cernvm-bot cloudtest

2023-05-17 13:32 UTC, HereThereBeDragons commented
@cernvm-bot cloudtest

2023-05-17 16:07 UTC, HereThereBeDragons commented
`test 811` fails sometimes with errno 10: No child processes 
in 
 https://github.com/cvmfs/cvmfs/blob/5d9a676aefc000b22786d429ee0bb60da938d5c5/cvmfs/publish/cmd_enter.cc#L671
 
 should it be there more tolerant? and also be a success if the child is already dead?

2023-05-22 09:09 UTC, jblomer requested changes
LGTM, just a few minor comments

2023-05-22 09:09 UTC, jblomer commented on cvmfs/monitor.h
> +#include <vector>
Not needed

2023-05-22 09:09 UTC, jblomer commented on cvmfs/monitor.h
> +   * All signals overwritten by the
```suggestion
   * All signals overwritten by the monitor
```

2023-05-22 09:09 UTC, jblomer commented on cvmfs/monitor.h
> +  static int all_signals[13];
Indicate as a global:
```suggestion
  static int g_all_signals[13];
```

2023-05-22 09:09 UTC, jblomer commented on cvmfs/monitor.h
> +  static int crash_signals[8];
```suggestion
  static int g_crash_signals[8];
```

2023-05-22 11:30 UTC, HereThereBeDragons commented on cvmfs/monitor.h
> +  static int all_signals[13];
// The watchdog is not supposed to receive signals. If it does, report it.

I therefore suggest renaming it to `g_suppressed_signals`

2023-05-22 11:34 UTC, HereThereBeDragons commented
@cernvm-bot cloudtest

2023-05-22 11:50 UTC, HereThereBeDragons commented
@cernvm-bot cloudtest

2023-05-22 12:28 UTC, jblomer approved these changes

2023-05-24 08:17 UTC, HereThereBeDragons commented
@cernvm-bot cloudtest

2023-06-22 07:36 UTC, vvolkl approved these changes

2023-06-22 07:37 UTC, merged