Proper construction/destruction of JobInfo class
cvmfs/cvmfs pull request #3295
Opened 2023-06-20 15:56 UTC by HereThereBeDragons

Issue #3095 
Supersedes #3221 

and includes unittests for sinks

2023-06-20 15:57 UTC, HereThereBeDragons commented
@cernvm-bot cloudtest

2023-06-20 15:58 UTC, HereThereBeDragons commented
@cernvm-bot help

2023-06-20 15:58 UTC, HereThereBeDragons commented
@cernvm-bot cpplint

2023-06-20 15:59 UTC, HereThereBeDragons commented
@cernvm-bot tidy

2023-06-20 15:59 UTC, HereThereBeDragons commented
@cernvm-bot unittest

2023-06-21 09:08 UTC, HereThereBeDragons commented
@cernvm-bot cloudtest cc8

2023-06-21 15:54 UTC, HereThereBeDragons commented
@cernvm-bot cloudtest

2023-06-22 08:02 UTC, HereThereBeDragons commented
@cernvm-bot cloudtest

2023-06-22 09:50 UTC, HereThereBeDragons commented
@cernvm-bot cloudtest

2023-06-22 13:19 UTC, HereThereBeDragons commented
@cernvm-bot cloudtest

2023-06-22 13:41 UTC, vvolkl commented
@cernvm-bot cloudtest

2023-06-22 15:20 UTC, HereThereBeDragons commented
@cernvm-bot cloudtest

2023-07-12 11:38 UTC, HereThereBeDragons commented
@cernvm-bot cloudtest

2023-07-12 14:37 UTC, HereThereBeDragons commented
for cloudtest failure also see https://lcgapp-services.cern.ch/cvmfs-jenkins/job/CvmfsCloudTesting/1780/ which is build on top of this branch. 
there only [ServerIntegrationTests.Commit command in a repository connected to the gateway](https://lcgapp-services.cern.ch/cvmfs-jenkins/job/CvmfsCloudTesting/1780/CVMFS_PLATFORM=debian11,CVMFS_PLATFORM_CONFIG=x86_64,label=trampoline/testReport/(root)/ServerIntegrationTests/Commit_command_in_a_repository_connected_to_the_gateway/) fails on debian

2023-07-13 22:20 UTC, jblomer requested changes
Very nice! We may need to come back to the `JobInfo` object at some point but this is strictly better than before!

One larger change is sticking to constructors rather than the factory methods, to avoid a bunch of heap allocations. This unfortunately triggers changes everywhere where `JobInfo` is used, but at least it should be a schematic change.

2023-07-13 22:20 UTC, jblomer commented on cvmfs/network/jobinfo.h
>    // Internal state, don't touch
It's already private
```suggestion
  // Internal state
```

2023-07-13 22:20 UTC, jblomer commented on cvmfs/network/jobinfo.h
> +  static JobInfo* CreateWithoutSink(const std::string *u, const bool ph);
Let's keep two regular constructor overloads instead. The advantage, in this case, is that we avoid heap additional allocations.  We should also document the effect of the two constructors (GET vs HEAD request).

2023-07-13 22:20 UTC, jblomer commented on cvmfs/network/jobinfo.h
> +  // Getter Pointer
remove

2023-07-13 22:20 UTC, jblomer commented on cvmfs/network/jobinfo.h
> +  // Getter
Remove

2023-07-14 07:39 UTC, HereThereBeDragons commented on cvmfs/network/jobinfo.h
> +  // Getter Pointer
i think we had this discussion before: its used in `repository.cc`

2023-07-14 10:07 UTC, HereThereBeDragons commented
@cernvm-bot cloudtest

2023-07-14 11:21 UTC, HereThereBeDragons commented
@cernvm-bot help

2023-07-14 11:21 UTC, HereThereBeDragons commented
@cernvm-bot cloudtest cc7

2023-07-14 13:59 UTC, HereThereBeDragons commented
@cernvm-bot cloudtest

2023-07-14 14:14 UTC, jblomer commented
See clang-tidy reported defects: https://lcgapp-services.cern.ch/cvmfs-jenkins/job/CvmfsTidy/label=docker-x86_64/915/artifact/tidy.out/*view*/

2023-07-14 14:27 UTC, jblomer approved these changes
Very nice improvement!

2023-07-14 15:21 UTC, HereThereBeDragons commented
@cernvm-bot cloudtest

2023-07-18 12:51 UTC, vvolkl commented on test/unittests/t_sink.cc
> +  cvmfs::FileSink sink(NULL);
```suggestion
  cvmfs::PathSink sink(NULL);
```

2023-07-19 07:36 UTC, vvolkl requested changes
Looks good to me apart from the typo in the unittests.

2023-07-19 08:55 UTC, HereThereBeDragons commented
@cernvm-bot  cloudtest

2023-07-19 08:55 UTC, HereThereBeDragons commented on test/unittests/t_sink.cc
> +  cvmfs::FileSink sink(NULL);
good catch, thanks

2023-07-19 11:40 UTC, merged