extend grep filter to accept microsecond precision in tags
cvmfs/cvmfs pull request #3301
Opened 2023-06-30 20:06 UTC by rptaylor

In some cases the tag names have have extra precision in their timestamps. This extends the filter to accept a potential dot and up to 3 digits for microseconds.

Fix https://github.com/cvmfs/cvmfs/issues/3271

It works based on this simple test:
```
$ cat tags
generic-2023-05-04T22:00:25Z     │    13476 │ 4 May 2023 15:00:49  │        │ 
generic-2023-05-04T22:51:06Z     │    13478 │ 4 May 2023 15:51:27  │        │ 
generic-2023-05-05T21:20:12.918Z │    13480 │ 5 May 2023 14:20:13  │        │ 
generic-2023-05-07T15:05:56.115Z │    13481 │ 7 May 2023 08:05:57  │        │ 
generic-2023-05-07T15:05:56Q115Z │    13481 │ 7 May 2023 08:05:57  │        │ 
# previous filter
$ grep -E  '^generic(_[[:digit:]]+)?-[[:digit:]]{4}-[[:digit:]]{2}-[[:digit:]]{2}T[[:digit:]]{2}:[[:digit:]]{2}:[[:digit:]]{2}Z' tags
generic-2023-05-04T22:00:25Z     │    13476 │ 4 May 2023 15:00:49  │        │ 
generic-2023-05-04T22:51:06Z     │    13478 │ 4 May 2023 15:51:27  │        │ 
# updated filter
$ grep -E '^generic(_[[:digit:]]+)?-[[:digit:]]{4}-[[:digit:]]{2}-[[:digit:]]{2}T[[:digit:]]{2}:[[:digit:]]{2}:[[:digit:]]{2}\.?[[:digit:]]{0,3}Z' tags
generic-2023-05-04T22:00:25Z     │    13476 │ 4 May 2023 15:00:49  │        │ 
generic-2023-05-04T22:51:06Z     │    13478 │ 4 May 2023 15:51:27  │        │ 
generic-2023-05-05T21:20:12.918Z │    13480 │ 5 May 2023 14:20:13  │        │ 
generic-2023-05-07T15:05:56.115Z │    13481 │ 7 May 2023 08:05:57  │        │ 
```

2023-06-30 20:07 UTC, rptaylor commented
@HereThereBeDragons this is an important fix required for GC to run in our environment, could we get it in 2.11 or a 2.10.x ?

2023-07-03 05:11 UTC, jblomer commented
@cernvm-bot cloudtest

2023-07-03 09:28 UTC, HereThereBeDragons requested changes

2023-07-03 09:28 UTC, HereThereBeDragons commented on cvmfs/server/cvmfs_server_publish.sh
> +    '^generic(_[[:digit:]]+)?-[[:digit:]]{4}-[[:digit:]]{2}-[[:digit:]]{2}T[[:digit:]]{2}:[[:digit:]]{2}:[[:digit:]]{2}\.?[[:digit:]]{0,3}Z' | \
i think the added regex needs to be changed a bit to  `(\.[[:digit:]]{1,3})?`
```
^generic(_[[:digit:]]+)?-[[:digit:]]{4}-[[:digit:]]{2}-[[:digit:]]{2}T[[:digit:]]{2}:[[:digit:]]{2}:[[:digit:]]{2}(\.[[:digit:]]{1,3})?Z
```

in your case the dot (.) is not mandatory. so it is ok to have `2 digits <no dot> up to 3 digits` which creates at least 2 invalid cases:
```
generic_2-2023-05-07T15:05:56115Z // would be valid but should not
generic_2-2023-05-07T15:05:56.Z // would be valid but should not
```

the new version with the brackets should enforce that the entire construct `.{1-3 digits}` must be  there or not at all.

2023-07-05 09:46 UTC, HereThereBeDragons approved these changes

2023-07-05 15:53 UTC, vvolkl commented
@cernvm-bot cloudtest

2023-07-05 16:09 UTC, jblomer approved these changes

2023-07-06 08:27 UTC, vvolkl approved these changes

2023-07-06 08:27 UTC, vvolkl commented
Test failure unrelated

2023-07-06 08:28 UTC, merged