update to support latest signature of fuse_lowlevel_notify_expire_entry
cvmfs/cvmfs pull request #3352
Opened 2023-08-03 08:50 UTC by HereThereBeDragons

2023-08-03 08:50 UTC, HereThereBeDragons commented
@cernvm-bot cloudtest

2023-08-03 10:02 UTC, jblomer requested changes
Great! Some minor comments.

2023-08-03 10:02 UTC, jblomer commented on cvmfs/fuse_evict.h
> +                bool fuse_notify_invalidation);
Since we already define the friend tests, can we make this constructor private?

2023-08-03 10:02 UTC, jblomer commented on cvmfs/fuse_evict.h
> +#include "mountpoint.h"
Should be enough to include in the compilation unit. Here, we can forward declare the `MounPoint` class.

2023-08-03 10:02 UTC, jblomer commented on cvmfs/fuse_evict.cc
> +*/
Comment only once, either here or in the header.

2023-08-03 10:02 UTC, jblomer commented on cvmfs/fuse_evict.cc
> +
```suggestion
```

2023-08-03 10:02 UTC, jblomer commented on cvmfs/fuse_evict.cc
> +
```suggestion
```

2023-08-03 10:02 UTC, jblomer commented on test/src/702-symlink_caching/main
> +# TODO TODO
```suggestion
# TODO(HereThereBeDragons)
```

2023-08-03 11:50 UTC, HereThereBeDragons commented
@cernvm-bot cloudtest

2023-08-03 12:06 UTC, jblomer approved these changes

2023-08-03 14:17 UTC, HereThereBeDragons commented
Related issue #2949

2023-08-03 22:35 UTC, vvolkl commented
There's a build failure on debian 12: https://lcgapp-services.cern.ch/cvmfs-jenkins/job/CvmfsFullBuildDocker/CVMFS_BUILD_ARCH=docker-x86_64,CVMFS_BUILD_PLATFORM=debian12/4049/console

2023-08-04 07:13 UTC, jblomer commented
Is this one of the buggy fuse versions?

2023-08-04 07:45 UTC, HereThereBeDragons commented
@cernvm-bot unittest

2023-08-04 07:45 UTC, HereThereBeDragons commented
@cernvm-bot cloudtest

2023-08-04 10:12 UTC, vvolkl approved these changes

2023-08-04 13:25 UTC, merged