downloadmanager: replace fini by destructor
cvmfs/cvmfs pull request #3436
Opened 2023-11-08 12:56 UTC by HereThereBeDragons

Issue #3095

2023-11-08 14:16 UTC, HereThereBeDragons commented
@cernvm-bot cloudtest

2023-11-09 14:00 UTC, HereThereBeDragons commented
@cernvm-bot cloudtest

2023-11-12 23:06 UTC, jblomer requested changes

2023-11-12 23:06 UTC, jblomer commented on cvmfs/network/download.h
> +   * pointers are used to allow for proper clean-up afterwards in destructor
```suggestion
   * pointers are used to allow for proper clean-up afterwards in the destructor
```

2023-11-12 23:06 UTC, jblomer commented on cvmfs/network/download.h
> +   * pointers are used to allow for proper clean-up afterwards in destructor
```suggestion
   * pointers are used to allow for proper clean-up afterwards in the destructor
```

2023-11-12 23:06 UTC, jblomer commented on cvmfs/network/download.cc
> +  if (opt_host_chain_) {
No `NULL` check around `delete` (also further down). It's already done by `delete`.

2023-11-12 23:06 UTC, jblomer commented on cvmfs/mountpoint.cc
>    if (external_download_mgr_ != NULL) {
Remove `if`, too

2023-11-12 23:06 UTC, jblomer commented on cvmfs/mountpoint.cc
>    if (download_mgr_ != NULL) {
Remove

2023-11-13 13:51 UTC, HereThereBeDragons commented
@cernvm-bot cloudtest

2023-11-13 14:37 UTC, jblomer approved these changes

2023-11-14 09:06 UTC, vvolkl commented
@cernvm-bot cloudtest

2023-11-14 14:15 UTC, merged