Detect directory entry modifications to uid/gid
cvmfs/cvmfs pull request #3473
Opened 2024-01-09 16:42 UTC by jblomer

Partially fixes #3435: uid/gid changes are now properly handled

2024-02-05 22:46 UTC, jblomer commented
@cernvm-bot unittest

2024-02-06 08:30 UTC, vvolkl commented
@cernvm-bot cloudtest

2024-02-22 13:27 UTC, vvolkl commented
@cernvm-bot  cloudtest

2024-10-15 20:50 UTC, vvolkl commented
@cernvm-bot cloudtest

2024-11-19 15:08 UTC, vvolkl commented
@cernvm-bot cloudtest

2024-11-19 16:14 UTC, vvolkl commented
@cernvm-bot cloudtest

2024-11-19 18:53 UTC, vvolkl requested changes

2024-11-19 18:53 UTC, vvolkl commented on cvmfs/swissknife_check.cc
> +  }
```suggestion
  if (!is_transition_point) {
      if (diffs & Difference::kUid) {
        LogCvmfs(kLogCvmfs, kLogStderr, "uids differ: %d / %d (%s / %s)",
                 a.uid(), b.uid(), a.name().c_str(), b.name().c_str());
        retval = false;
      }
      if (diffs & Difference::kGid) {
        LogCvmfs(kLogCvmfs, kLogStderr, "gids differ: %d / %d (%s / %s)",
                 a.gid(), b.gid(), a.name().c_str(), b.name().c_str());
        retval = false;
      }
    }
```
This check should not should fail for nested catalog transition points. There could be a `catalog-chown` that is not expected to affect them, I think.

2024-11-21 16:30 UTC, vvolkl commented on cvmfs/swissknife_check.cc
> +  }
Commiting in order to start cloudtests

2024-11-21 16:31 UTC, vvolkl commented
@cernvm-bot cloudtest

2024-11-22 08:57 UTC, vvolkl approved these changes

2024-11-22 09:00 UTC, merged