DownloadMgr: Better tracking of JobInfo object and its respective CURL requests
cvmfs/cvmfs pull request #3492
Opened 2024-01-30 15:15 UTC by HereThereBeDragons

- introduces a monotonically increasing id for each jobinfo element
- nearly all debuglog messages now include this jobinfo id 
- also CURL debuglog callback function will print this jobinfo id

- new logging of how many redirects CURL followed on its own
- if CURL data is less than 50 char it will try to prin it to debug in plaintext if it is valid char codes and not weird binary data

2024-01-30 15:18 UTC, HereThereBeDragons commented
linter complains are unrelated...

2024-01-30 15:22 UTC, HereThereBeDragons commented
example output:

```
(download) requesting ordered server list from http://cvmfs-s1bnl.opensciencegrid.org:8000/cvmfs/des.osgstorage.org/api/v1.0/geo/@proxy@/cvmfs-egi.gridpp.rl.ac.uk,cvmfs-s1.hpc.swin.edu.au,cvmfs-s1bnl.opensciencegrid.org,cvmfs-s1fnal.opensciencegrid.org,cvmfs-s1goc.opensciencegrid.org,cvmfs-stratum-one.ihep.ac.cn,klei.nikhef.nl,sampacs01.if.usp.br    [01-30-2024 15:59:45 CET]
(download) (id 1) replacing @proxy@ by caproxylbp.cern.ch    [01-30-2024 15:59:45 CET]
(download) (id 1) escaped http://cvmfs-s1bnl.opensciencegrid.org:8000/cvmfs/des.osgstorage.org/api/v1.0/geo/caproxylbp.cern.ch/cvmfs-egi.gridpp.rl.ac.uk,cvmfs-s1.hpc.swin.edu.au,cvmfs-s1bnl.opensciencegrid.org,cvmfs-s1fnal.opensciencegrid.org,cvmfs-s1goc.opensciencegrid.org,cvmfs-stratum-one.ihep.ac.cn,klei.nikhef.nl,sampacs01.if.usp.br to http://cvmfs-s1bnl.opensciencegrid.org:8000/cvmfs/des.osgstorage.org/api/v1.0/geo/caproxylbp.cern.ch/cvmfs-egi.gridpp.rl.ac.uk,cvmfs-s1.hpc.swin.edu.au,cvmfs-s1bnl.opensciencegrid.org,cvmfs-s1fnal.opensciencegrid.org,cvmfs-s1goc.opensciencegrid.org,cvmfs-stratum-one.ihep.ac.cn,klei.nikhef.nl,sampacs01.if.usp.br    [01-30-2024 15:59:45 CET]
(curl) (id 1) {header/sent} GET http://cvmfs-s1bnl.opensciencegrid.org:8000/cvmfs/des.osgstorage.org/api/v1.0/geo/caproxylbp.cern.ch/cvmfs-egi.gridpp.rl.ac.uk,cvmfs-s1.hpc.swin.edu.au,cvmfs-s1bnl.opensciencegrid.org,cvmfs-s1fnal.opensciencegrid.org,cvmfs-s1goc.opensciencegrid.org,cvmfs-stratum-one.ihep.ac.cn,klei.nikhef.nl,sampacs01.if.usp.br HTTP/1.1
Host: cvmfs-s1bnl.opensciencegrid.org:8000
Accept: */*
Proxy-Connection: Keep-Alive
Connection: Keep-Alive
User-Agent: cvmfs Fuse 2.12.0    [01-30-2024 15:59:45 CET]
(curl) (id 1) {header/recv} HTTP/1.1 200 OK    [01-30-2024 15:59:46 CET]
(curl) (id 1) {header/recv} Date: Tue, 30 Jan 2024 14:59:46 GMT    [01-30-2024 15:59:46 CET]
(curl) (id 1) {header/recv} Server: Apache/2.4.6 (Red Hat Enterprise Linux)    [01-30-2024 15:59:46 CET]
(curl) (id 1) {header/recv} Cache-Control: max-age=3600    [01-30-2024 15:59:46 CET]
(curl) (id 1) {header/recv} Content-Security-Policy: frame-ancestors 'self' *.bnl.gov    [01-30-2024 15:59:46 CET]
(curl) (id 1) {header/recv} Content-Length: 16    [01-30-2024 15:59:46 CET]
(curl) (id 1) {header/recv} Content-Type: text/plain; charset=UTF-8    [01-30-2024 15:59:46 CET]
(curl) (id 1) {header/recv} X-Cache: MISS from cvmfs-reverse4.sdcc.bnl.gov    [01-30-2024 15:59:46 CET]
(curl) (id 1) {header/recv} X-Cache: MISS from ca-mey-frontier-485577af8b.cern.ch    [01-30-2024 15:59:46 CET]
(curl) (id 1) {header/recv} Via: 1.1 cvmfs-reverse4.sdcc.bnl.gov (squid/frontier-squid-5.9-1.1), 1.1 ca-mey-frontier-485577af8b.cern.ch (squid/frontier-squid-4.15-2.1)    [01-30-2024 15:59:46 CET]
(curl) (id 1) {header/recv} Connection: keep-alive    [01-30-2024 15:59:46 CET]
(curl) (id 1) {header/recv}     [01-30-2024 15:59:46 CET]
(curl) (id 1) {data/recv} 7,1,3,4,5,6,8,2    [01-30-2024 15:59:46 CET]
(download) (id 1) Verify downloaded url http://cvmfs-s1bnl.opensciencegrid.org:8000/cvmfs/des.osgstorage.org/api/v1.0/geo/@proxy@/cvmfs-egi.gridpp.rl.ac.uk,cvmfs-s1.hpc.swin.edu.au,cvmfs-s1bnl.opensciencegrid.org,cvmfs-s1fnal.opensciencegrid.org,cvmfs-s1goc.opensciencegrid.org,cvmfs-stratum-one.ihep.ac.cn,klei.nikhef.nl,sampacs01.if.usp.br, proxy http://188.184.31.232:3128 (curl error 0)    [01-30-2024 15:59:46 CET]
(download) geographic order of servers retrieved from cvmfs-s1bnl.opensciencegrid.org    [01-30-2024 15:59:46 CET]
(download) order is 7,1,3,4,5,6,8,2    [01-30-2024 15:59:46 CET]
(download) switching proxy from (none) to http://137.138.150.196:3128 (cloned)    [01-30-2024 15:59:46 CET]

...
(curl) (id 8) {header/recv} Content-Length: 0    [01-30-2024 15:59:57 CET]
(curl) (id 8) {header/recv}     [01-30-2024 15:59:57 CET]
(curl) (id 8) {header/sent} GET /pnfs/fnal.gov/usr/des/persistent/stash/kherner/load_testing/uboonebeam/beam_data/bnb_data/00/01/90/75/beamdata_00019075.root?dcache-http-uuid=e7366ea9-0dd5-4cc3-9b80-deeea1b3b1f6&dcache-http-ref=http%3A%2F%2Ffndca1.fnal.gov%3A8000 HTTP/1.1
Host: [2620:6a:0:4812:f0:0:69:198]:23748
Accept: */*
Connection: Keep-Alive
User-Agent: cvmfs Fuse 2.12.0
cvmfs-info: /pnfs/fnal.gov/usr/des/persistent/stash/kherner/load_testing/uboonebeam/beam_data/bnb_data/00/01/90/75/beamdata_00019075.root    [01-30-2024 15:59:57 CET]
(curl) (id 6) {data/recv} <snip>    [01-30-2024 15:59:57 CET]
(curl) (id 6) {data/recv} <snip>    [01-30-2024 15:59:57 CET]
(curl) (id 6) {data/recv} <snip>    [01-30-2024 15:59:57 CET]

``

2024-01-31 09:59 UTC, HereThereBeDragons commented
@cernvm-bot cloudtest

2024-01-31 10:11 UTC, HereThereBeDragons commented
these unrelated linter errors i can treat in the PR to move `tube.h`

2024-02-01 08:39 UTC, vvolkl commented
Having the id monotonically increasing is nice, but any unique identifier would be sufficient, right? I wonder if there is already something in JobInfo that would let us avoid the atomic add (I doubt the performance overhead is big, but still). Is the value of the pointer to the curl handle stable und unique enough? If so we could just log that

2024-02-02 09:10 UTC, HereThereBeDragons commented
the idea of curl handles is to reuse them. so there might be difficulties to distinguish them if they are immediately reused.

as another solution we can do the id stuff only when in debug mode and otherwise just set the id to `-1` for all jobinfo elements

let me know what you prefer

2024-02-05 15:51 UTC, jblomer commented
Hm, not sure if we can rely on anything unique in the `JobInfo` itself. An atomic counter looks very robust to me, and since we are anyway doing I/O, the atomic operation should not hurt...

2024-02-05 15:58 UTC, jblomer approved these changes
LG (some minor comments)

2024-02-05 15:58 UTC, jblomer commented on cvmfs/network/jobinfo.h
> +  static atomic_int64 next_uuid;
Private?

2024-02-05 15:58 UTC, jblomer commented on cvmfs/network/download.cc
> +        int64_t countp;
```suggestion
        int64_t redir_count;
```

2024-02-05 15:59 UTC, jblomer commented on cvmfs/network/download.cc
> +          "%sswitching host from %s to %s (%s)", info_id.c_str(),
```suggestion
          "switching host from %s to %s (%s)", info_id.c_str(),
```

2024-02-05 16:00 UTC, jblomer requested changes
Oh, one critical issue though!

2024-02-05 16:00 UTC, jblomer commented on cvmfs/network/download.cc
> +          "%sswitching host from %s to %s (%s)", info_id.c_str(),
```suggestion
          "switching host from %s to %s (%s)", info_id.c_str(),
```

2024-02-06 08:47 UTC, HereThereBeDragons commented on cvmfs/network/download.cc
> +          "%sswitching host from %s to %s (%s)", info_id.c_str(),
no.

please have a look at lines 2172 and 2175. it is either an empty string (if jobinfo == NULL) or the job info id

https://github.com/cvmfs/cvmfs/blob/94d9aa104752dcd5ba338014860969ac413d9c9a/cvmfs/network/download.cc#L2172-L2176

2024-02-06 08:48 UTC, HereThereBeDragons commented on cvmfs/network/download.cc
> +          "%sswitching host from %s to %s (%s)", info_id.c_str(),
we can add another space before `"%sswitchng` and change it to `"%s switching` but this will create a not so nice formatting if jobinfo is null

2024-02-06 08:58 UTC, jblomer approved these changes

2024-02-06 08:58 UTC, jblomer commented on cvmfs/network/download.cc
> +          "%sswitching host from %s to %s (%s)", info_id.c_str(),
Ok, I missed the `info_id.c_str()`. Fine as is.

2024-02-06 08:59 UTC, jblomer commented
@cernvm-bot cpplint

2024-02-06 08:59 UTC, jblomer commented
@cernvm-bot unittest

2024-02-06 09:00 UTC, HereThereBeDragons commented
i still need to fix your 2 other requests

2024-02-06 09:44 UTC, HereThereBeDragons commented
this should now be everything - unless you want to do the counter increase only for debug

2024-02-06 09:44 UTC, HereThereBeDragons commented
@cernvm-bot cloudtest

2024-02-06 14:24 UTC, vvolkl commented
> this should now be everything - unless you want to do the counter increase only for debug

No, I think it's good as is, the improved log does make up for the complexity - performance is likely no issue.

2024-02-06 14:24 UTC, vvolkl approved these changes

2024-02-06 14:28 UTC, vvolkl commented
@cernvm-bot unittest

2024-02-07 07:30 UTC, merged