Remove Taiwan stratum 1 from config rpm for egi and osg
cvmfs/cvmfs pull request #3669
Opened 2024-09-24 15:43 UTC by DrDaveD

Remove the ASGC Taiwan stratum 1 from the egi and opensciencegrid domains in the cvmfs-config-default rpm.

The list of stratum 1s is normally overriden by the configuration repository so this only affects cases where the configuration repository is not available.

2024-09-30 08:28 UTC, vvolkl commented
@cernvm-bot cloudtest

2024-10-01 12:00 UTC, vvolkl requested changes
We need a few more changes for a new config-default package, in particular a similar  update to the changelog for debian: `cvmfs/packaging/debian/config-default/changelog` and bumping the version numbers in the ci scripts:  `ci/cvmfs/rpm.sh` and ci/`cvmfs/deb.sh`. I'll go ahead and add those directly in your branch if that's ok.

2024-10-01 21:41 UTC, DrDaveD commented
Sure that's OK

2024-10-03 14:55 UTC, vvolkl approved these changes

2024-10-03 14:55 UTC, merged