better description for EIO logging
cvmfs/cvmfs pull request #3723
Opened 2024-12-05 10:32 UTC by HereThereBeDragons

Issue #3705

i would also like to change the numbering for the EIO. it should be consistent that EIO in the same funciton are linearly increasing

2025-01-21 07:43 UTC, vvolkl requested changes
Looks good to me if you remove the unrelated whitespace changes.

2025-01-22 09:02 UTC, HereThereBeDragons commented
the whitespace removal is what cpplint wants and was forgotten because cpplint was broken.

do you still want me to add the whitespace back which shouldnt be there in the first place?

2025-01-22 09:46 UTC, vvolkl commented
Yes, in the interest of the git history let's keep commits focused on one particular change. We'll anyway run clang-format on the codebase, but in a separate PR.

2025-01-23 14:15 UTC, vvolkl approved these changes

2025-01-23 14:15 UTC, vvolkl commented
@cernvm-bot cloudtest

2025-03-03 20:56 UTC, vvolkl commented
@cernvm-bot  cloudtest

2025-03-04 10:16 UTC, vvolkl commented
@cernvm-bot cloudtest

2025-03-04 14:09 UTC, vvolkl commented
@cernvm-bot cloudtest

2025-03-04 15:57 UTC, vvolkl requested changes
Test 690 consistently fails on some platforms with this patch, needs to be investigated

2025-04-28 07:12 UTC, vvolkl commented
@cernvm-bot cloudtest

2025-04-29 09:37 UTC, HereThereBeDragons commented
@cernvm-bot cloudtest

2025-04-30 06:50 UTC, vvolkl approved these changes

2025-04-30 06:51 UTC, merged